# name: Deploy to S3

# on:
#   push:
#     branches: [main]  # Trigger this when code is pushed to main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: sa-east-1

#       - name: Deploy to S3
#         run: aws s3 sync . s3://textstadia  --delete


# name: Deploy to S3

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v7

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v6
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: sa-east-1

#       - name: Deploy to S3
#         run: aws s3 sync . s3://my-static-site-bucket1557665-932877337538-sa-east-1-an  --delete --exclude ".git*"


name: Deploy to S3

on:
  push:
    branches: [main]

# Required permissions for OIDC token authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{vars.AWS_GITHUB_ARN}}
          aws-region: sa-east-1

      - name: Deploy to S3
        run: aws s3 sync . s3://my-static-site-bucket1557665-932877337538-sa-east-1-an  --delete --exclude ".git*"
